Login store
moscugeorge123/dsc-frontend-2020 pull request #31
Opened 2020-04-14 17:27 UTC by RasterDX

2020-04-27 14:56 UTC, moscugeorge123 requested changes

2020-04-27 14:56 UTC, moscugeorge123 commented on src/app/session/services/auth-guard.service.ts
>  import { Injectable } from '@angular/core';
change this file to be the same as master

2020-04-27 14:56 UTC, moscugeorge123 commented on src/app/session/services/nonauth-guard.service.ts
>  import { Injectable } from '@angular/core';
change this file to be the same as master

2020-04-27 14:56 UTC, moscugeorge123 commented on src/app/session/services/session.service.ts
> +  private url: string = "http://localhost:1337";
remove this as you don't need it

2020-04-27 14:56 UTC, moscugeorge123 commented on src/app/session/store/reducers/login.reducers.ts
> +  on(SessionLoginSuccess, (state: ISessionState, payload: any) => ({
Here shouldn't be `(state: ISessionState, { payload })`?

2020-04-29 16:30 UTC, RazvanMaftei9 commented on src/app/session/store/reducers/login.reducers.ts
> +  on(SessionLoginSuccess, (state: ISessionState, payload: any) => ({
i dont think so, when i tested it it locally it worked just fine (and i dont know how i would access the payload data if i wrapped it in a js object)

2020-05-06 17:04 UTC, merged